nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.0.2.cjs
npmScopes:
  fortawesome:
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAlwaysAuth: true
    npmAuthToken: ${FONTAWESOME_NPM_AUTH_TOKEN}
